# Generated by Django 3.2.9 on 2021-12-12 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storelocation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='storelocation',
            name='state',
        ),
    ]
